# Generated by Django 5.1.7 on 2025-04-30 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_donor_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='mobile_number',
            field=models.CharField(default='0000000000', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='donor',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='donor',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
