# Generated by Django 5.1.7 on 2025-04-30 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_donor_mobile_number_alter_donor_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='address',
        ),
    ]
