# Generated by Django 5.1.7 on 2025-04-30 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_remove_donor_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('donor', 'Donor'), ('receiver', 'Receiver')], default='donor', max_length=10),
        ),
    ]
